### ISSUE TITLE
DeckHub - Kimliği belirsiz bir geliştiriciden geldiği için açılamıyor hatası

### ISSUE THREAD

**Issue by xJason21** [DeckHub/App#1]
<Your feedback content here>
Mailden tıkladığım indirme linki ile gelen dosyayı kurmaya çalıştığımda **"DeckHub" Kimliği belirsiz bir geliştiriciden geldiği için açılamıyor.** hatası alıyorum. Ekran görüntüsüne buradan [ulaşabilirsiniz.](https://twitter.com/xJason21/status/719993394752315393)
- Deckhub Version:  0.9.1
- Platform/OS & Version: El Capitan 10.11.2

<additional notes (if any)>

**Comment by atakangktepe** [comment]
Apple Logosuna tıklayıp "System Prefences" sekmesine girip "Security & Privacy" bölümüne girmelisin şu şekilde :
![1](https://cloud.githubusercontent.com/assets/12830048/14475933/71e6f6a6-010d-11e6-9463-59ee19208292.png)

Ardından kilit ikonuna tıklayıp şifreni gireceksin:
![2](https://cloud.githubusercontent.com/assets/12830048/14475945/91626e5c-010d-11e6-81ef-442742a9325f.png)

Daha sonra "Allows apps downloaded from" bölümünde "Anywhere" seçeneğini seçeceksin:
![3](https://cloud.githubusercontent.com/assets/12830048/14475979/c7f8d28a-010d-11e6-95eb-62f2ec8cea8f.png)

bu adımları takip ettikden sonra yükleyebilirsin.

**Comment by xJason21** [comment]
Çok teşekkür ederim detaylı anlatımın için @atakangktepe mac'te yeni olduğumu nasıl da belli etmişim :)

**Comment by burakcan** [comment]
Aciklama icin tesekkurler @atakangktpe :)

@xJason21 bu degisikligi yapmadan once o alanda hangisi seciliydi acaba?

**Comment by xJason21** [comment]
@burakcan AppStore ve kimliği belirli geliştiriciler seçiliydi, sanırım default ayar o olmalı.

**Comment by burakcan** [comment]
Tamamdir @xJason21 tesekkur ederiz. Bir sonraki versiyonda bu problemi duzeltmis olacagiz. Simdilik yukaridaki yontemle kullanmaya devam edebilirsin :)

**Comment by burakcan** [comment]
@xJason21 bu problem yeni versiyonda duzeldi. Artik o ayari yapmadan da kurabilirsin. Yeni versiyon emaillerde :confetti_ball:

**Comment by xJason21** [comment]
@burakcan eline saglik ama dun ben uygulamayi da gorebileyim diye Atakan'in yardimiyla o ayari yapip kurmustum, sorun degil cozulduyse ne mutlu :)
