### ISSUE TITLE
UI Problemleri

### ISSUE THREAD

**Issue by tahaipek** [DeckHub/App#10]
Selamlar,
Sanırım bu sürümde oldu, daha önce karşılaşmamıştım. 
Aşağıda yer alan resimde görüldüğü gibi;
- Akışlardaki veriler üst üste biniyor. (Kırmızı renkli)
- Bulunduğu container'ın dışına taşıyor. Overflow hidden olduğu için yazılar yarım görüntüleniyor. (Sarı renkli)
- Akışlardaki container'lar üst üste biniyor. (Mavi renkli)

Ekstra olarak, column'larda horizontal scroll gizlenmiş fakat, farenin orta tuşu ile scroll horizontal şekilde hareket ettirilebiliyor. (Çok mühim bir problem değil sanırım. :) )

Teşekkürler, kolay gelsin

- Deckhub Version: 0.9.2
- Platform/OS & Version: Wİndows 10 Pro

![image](https://cloud.githubusercontent.com/assets/5754670/14534296/254df320-0271-11e6-9d59-d432a4211c97.png)

**Comment by burakcan** [comment]
Bu sadece global timeline'da karsilasilan bir problemdi. Global timeline beta testerlar arasinda kullanilmayan (pratikte de pek faydasi yok zaten :) ) bir kolon oldugu icin bir sonraki versiyonda global timeline feed eklemeyi kaldiriyoruz.

**Comment by tahaipek** [comment]
Kötü olmuş. Alanımızla alakalı olmasada çok güzel ve farklı fikirler ortaya çıkıyordu.

**Comment by burakcan** [comment]
Bunun yerine daha farkli bir "Explore" kolonu uzerinde calisiyoruz :)
