### ISSUE TITLE
A javascript error poped at first time launch

### ISSUE THREAD

**Issue by vigo** [DeckHub/App#14]
<img width="1106" alt="screen shot 2016-04-16 at 11 03 02" src="https://cloud.githubusercontent.com/assets/82952/14579878/0057ae82-03c3-11e6-98c7-a0552d35cf53.png">

- Deckhub Version: 0.9.1
- Platform/OS & Version: osx 10.11.4

**Comment by burakcan** [comment]
This is fixed in 0.9.2. You can get it from the same link that we sent in beta email. Starting from 0.9.2, you'll get the updates automatically.
