### ISSUE TITLE
Lisans key hatası

### ISSUE THREAD

**Issue by kamilklkn** [DeckHub/App#16]
Küçük bir problem var,
 - Uygulamayı satın aldım,
 - Gelen lisans key  ve email bilgileri ile aktif ettim, aktif olduğuna dair olumlu mesajıda aldım.
 - Kapatıp yeniden açtığımda 15 günlük deneme sürümü görünüyor, lisans key ile aktif etmeye çalıştığımda da "We could not activate your licence. Please check your information and try again. If you think that this is a problem; please contact us at hey@getdeckhub.com" mesajı ile karşılaşıyorum.

- Deckhub Version: 1.0.0
- Platform/OS & Version: Windows

**Comment by burakcan** [comment]
@kamilklkn merhaba, lisans icin kayit oldugun email adresini kontrol etmemiz icin hey@getdeckhub.com adresine gonderebilir misin. Tesekkurler.

**Comment by kamilklkn** [comment]
Kapatıp yeniden açtım, tekrar etkinleştirdiğimde oldu.
