### ISSUE TITLE
Show the whole comment

### ISSUE THREAD

**Issue by amree** [DeckHub/App#24]
Is it possible to show the whole comment instead of clicking on the issue number to view it? That'll make reviewing new comment so much faster.

- Deckhub Version: `v1.0.0`
- Platform/OS & Version: `OS X 10.11.4 (15E65)`

**Comment by burakcan** [comment]
Hi @amree thank you for your feedback 💯 
We have some plans about this. Please see: https://github.com/DeckHub/App/issues/20

**Comment by mamree** [comment]
Ah, thanks for the feedback. I'll keep watch on that issue.
