### ISSUE TITLE
OAuth permissions - DeckHub needs write access to all my public + private repos?

### ISSUE THREAD

**Issue by jm3** [DeckHub/App#30]
Is that really necessary just, to try out the app? There's no read-only mode to at least look around?

What features does DeckHub does write-access to all my repo's + orgs enable that wouldn't work without write access?

![deckhub-perms](https://cloud.githubusercontent.com/assets/12213/14659641/a221f876-0652-11e6-87e8-5b9bef161a42.png)

**Comment by burakcan** [comment]
Hi @jm3,
There is an open letter to GitHub: https://github.com/dear-github/dear-github/
At there, there are some in open issues about this problem. There is no such a thing in github oauth api like 'read-only'.
And please note: We don't keep any of your sensitive data -including your access token- in our servers. So, this means we don't actually have access to your data but we know that it's hard to trust.  We are planning to introduce a 'only public' login in the following days.

**Comment by jm3** [comment]
1. My concern is less about a malicious attack, and more about bugs in new software. Giving write access where not needed is too much to ask.

2. GitHub may not support "read only" permissions, but they definitely support Public Repo access vs. private, which is the option DevSpace.io provides. I guess that's the choice you're referring to, which is coming soon? If so, cool, thank you. :)

**Comment by burakcan** [comment]
Hi @jm3, this feature is now live on 1.0.2 :) if you logged in before; you can revoke deckhub's access on GitHub settings and login again with only public access.

**Comment by jm3** [comment]
thanks!
