### ISSUE TITLE
Add support for GitLab

### ISSUE THREAD

**Issue by CameronBanga** [DeckHub/App#33]
Any thoughts on adding GitLab for the future? It's growing fairly heavily, and we have all of our private repos (aka anything we care about) there. Would make the app considerably more valuable for us (and an easy buy) if GitLab was also supported.

- Deckhub Version: 1.0.1
- Platform/OS & Version: OS X 10.11.4

**Comment by s** [comment]
Hi Cameron, Thank you for contacting us! To be honest, GitLab currently doesn’t offer as wide variety of APIs as we have currently on Github. So even though we have future plans to have this feature, I am sorry to say that it will not be fully functional and not include some functions such as events etc. In any case, thank you for supporting us! 
/Said
