### ISSUE TITLE
Started Repo Logları

### ISSUE THREAD

**Issue by dechub-qa** [DeckHub/App#7]
Merhabalar,

![2016-04-14 11_38_00-deckhub](https://cloud.githubusercontent.com/assets/18459005/14522220/38601ba4-0236-11e6-9d1c-6e7eec2da3de.png)

Picture de görüdğünüz üzere bir repo oluşturdum. Daha sonra bunu Deckhub üzerinde started (yıldıza tıkladım) ve create reponun üzerinde started repo log'u düştü. Aynı zamanda bunu gene kaldırdım gene yıldıza bastım. Ama loglar hala ACTIVITY tabın da duruyordu. 

Bu davranış normal mı?

- Deckhub Version: 0.9.2
- Platform/OS & Version:  Windows 10

<additional notes (if any)>

**Comment by burakcan** [comment]
Selam abi, 
Bu feed "kim starladi"dan con "ne oldu" feedi oldugu icin bu normal. Sonucta tarihin o zamaninda onu starladin.
