### ISSUE TITLE
Kullanıcı bazlı logları check etmek

### ISSUE THREAD

**Issue by dechub-qa** [DeckHub/App#8]
Selamlar,

ACTIVITY örnek olsun diye ekliyorum tabii ki, ACTIVITY e tıkladığımız da stream'ı böyle bi check ettirseniz güzel olmaz mı?  

Çünkü az önce repo açtım biraz geç düştü background'da ne oldu bilmiyorum ama bende bi tık ile check ettirebilseydim daha güzel olabilir diye düşündüm.
![2016-04-14 11_41_11-deckhub](https://cloud.githubusercontent.com/assets/18459005/14522349/c9ebb7c2-0236-11e6-9f12-f98340bfdb11.png)

- Deckhub Version: 0.9.2
- Platform/OS & Version:  Windows 10

<additional notes (if any)>

**Comment by burakcan** [comment]
related: https://github.com/DeckHub/App/issues/3

**Comment by burakcan** [comment]
Duplicate of issue #3
